# Generated by Django 4.2.2 on 2023-07-31 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='is_cancelled',
        ),
    ]
