# Generated by Django 4.2.2 on 2023-08-05 07:42

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_remove_hotelbooking_is_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
